### ISSUE TITLE
Question about GNSS component / checks for proper interference minimisation

### ISSUE THREAD

**Issue by StohanzlMart** [JITx-Inc/open-components-database#481]
Hello, love the idea behind the project. Though the only thing I cannot find is how to incorporate the info from Application Notes about placement ([i.e. PA1616D GNSS Module](https://www.cdtop-tech.com/products/pa1616d)), excerpt below.

![image](https://github.com/JITx-Inc/open-components-database/assets/31247214/1b9d65a5-9974-43d6-9849-371722fc289c)

Or how to put this text into the component model, or do I have to add checks to do that?

![image](https://github.com/JITx-Inc/open-components-database/assets/31247214/ec164f4d-0bd0-43e1-bd46-8105a2440ad8)

If the component can yield those constraints too (we had serious troubles with interference), I see no reason, why we don't buy your compiler & ui.

**Comment by bhusang** [comment]
Hi @StohanzlMart 

You have some good questions. Starting with the last one first is that you can define a ground pour as part of your landpattern for the device so that when you instantiate the device, you automatically instantiate a portion of the ground plane as you have defined it. 

In terms of placement, I think that with the appropriate code it should be possible to automate the placement. For an example of a code placed module, please take a look at our cookbook example of a regulator here: https://github.com/JITx-Inc/jitx-cookbook/tree/main/regulator_example I should also note that with the appropriate introspection on component sizes and pad locations, you can also place a design as we did here: https://github.com/JITx-Inc/jitx-cookbook/tree/main/usb_c_cable_tester

**Comment by bhusang** [comment]
@StohanzlMart Please join our discord channnel if you have further questions : https://discord.gg/EEDQFZWuhy
